services:
  mongo-db:
    container_name: "mongo-db"
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ./config/.env
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  mongo: