services:
  mongo-db:
    container_name: "mongo-db"
    image: mongo
    volumes:
      - ./mongo:/data/db
    env_file:
      - ./config/.env
  mongo-express:
    container_name: "mongo-express"
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./config/.env
  library-app:
    container_name: "library-app"
    image: library-app
    build:
      context: ./library-app
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./library-app:/usr/library-app
    depends_on:
      - mongo-db
    env_file:
      - ./config/.env
