services:
  mongo-db:
    container_name: "mongo-db"
    image: mongo
    networks: 
      - mongo-compose-network
    ports:
      - 27017:27017
    env_file:
      - ./config/.env
    volumes:
      - type: volume
        source: mongo
        target: /data/db
  mongo-express:
    container_name: "mongo-express"
    image: mongo-express
    networks: 
      - mongo-compose-network
    ports:
      - 8081:8081
    depends_on:
      - mongo-db
    env_file:
      - ./config/.env
    volumes:
      - type: volume
        source: mongo
        target: /data/db
  library-app:
    container_name: "library-app"
    image: library-app
    build:
      context: ./library-app
      dockerfile: Dockerfile
    networks: 
      - mongo-compose-network
    ports:
      - 80:3000
    depends_on:
      - mongo-db
    env_file:
      - ./config/.env
    volumes:
      - ./library-app:/usr/library-app

networks:
  mongo-compose-network:
    driver: bridge
volumes:
  mongo: